config/routes.rb
Rails.application.routes.draw do

  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/admin/graph_ql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'residential' => 'pages#residential'
  get 'corporate' => 'pages#corporate'
  get 'quote' => 'quotes#new'
  get 'thanks' => 'pages#thanks'
  get 'thanksleads' => 'pages#thanksleads'
  get 'career' => 'careers#new'
  get 'subscription' => 'subscriptions#new'
  get 'thanksquote' => 'pages#thanksquote'
  get 'thankssubs' => 'pages#thankssubs'
  get 'watson' => 'watson#watson'
  get 'interventions' => 'index#interventions'
  post 'interventions' => 'index#interventions'

  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'

  resources :quotes
  resources :careers
  resources :subscriptions
  resources :leads
  resources :interventions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    puts "*****************************************************"
    puts "CREATE SUBSCRIPTIONS"
    puts params
    puts subscription_params
    @subscription = Subscription.new(subscription_params)
    puts "*******************************************************"
    #@subscription.save = subscription_params[:subscription]

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to thankssubs_path, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.permit(:subscription)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<title>Rocket Elevators</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true%>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

<meta charset="utf-8" />
	<meta name="description" content="" />
	<meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />

	<!-- mobile settings -->
	<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
	<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

	<!-- WEB FONTS : use %7C instead of | (pipe) -->
	<!--<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />-->
	<link href="https://fonts.google.com/specimen/Roboto" rel="stylesheet" type="text/css" />
	
	
</head>

<body>

<div id="slidetop">

		<div class="container">

			<div class="row">

				<div class="col-md-4">
					<h6><i class="icon-heart"></i> A MESSAGE FROM OUR PRESIDENT</h6>
					<p>We have chosen to live by 3 core values: Integrity, Service, and Quality, and these words are more than a
						poster hanging in our office; each week we share stories of how these core values are being lived out by our
						team. I am very proud that we are a top TSSA elevator contractor in America, and that we were nominated for
						“Best
						Contractor in America”. I am most pleased, however, by the comments we continually receive from our satisfied
						customers, as attested by our 4.9/5.0 Google Review Score and Comments. I hope you decide to give Elevator One a
						try. I am sure you won’t be disappointed.”</p>
				</div>

				<div class="col-md-4">
					<h6><i class="fa-facheck"></i> WHY US ?</h6>
					<ul class="list-unstyled">
						<li><a href="#"><i class="fa fa-angle-right"></i> Professional technicians.</a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i> We design, evaluate and justify technology solutions.</a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i> Largest market share throughout Central America.</a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i> Because of our superior service.</a></li>
						<li><a href="#"><i class="fa fa-angle-right"></i> Every Rocket home elevator includes warranty.</a></li>
					</ul>
				</div>

				<div class="col-md-4">
					<h6><i class="icon-envelope"></i> CONTACT INFO</h6>
					<ul class="list-unstyled">
						<li><b>Address:</b> Québec, QC G2J 0C4<br />Boulevard Lebourgneuf,</li>
						<li><b>Phone:</b> (418) 580-7055</li>
						<li><b>Email:</b> <a href="rocketeleveator@codeboxx.biz">rocketeleveator@codeboxx.biz</a></li>
					</ul>
				</div>

			</div>

		</div>

		<a class="slidetop-toggle" href="#">
			<!-- toggle button --></a>

	</div>
	<!-- /SLIDE TOP -->




	<!-- wrapper -->
	<div id="wrapper">

		<!-- 
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.b-0 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!

				Example Usage:  class="clearfix sticky header-sm transparent b-0"
			-->
		<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

			<!-- TOP NAV -->
			<header id="topNav">
				<div class="container">

					<!-- Mobile Menu Button -->
					<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
						<i class="fa fa-bars"></i>
					</button>

					<!-- BUTTONS -->
					<ul class="float-right nav nav-pills nav-second-main">

						

					</ul>
					<!-- /BUTTONS -->

					<!-- Logo -->
					<a class="logo float-left" href="index.html">
						<%= image_tag("R2.png", :alt => "logo") %>
					
					</a>

					<!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
					<div class="navbar-collapse collapse float-right nav-main-collapse">
						<nav class="nav-main">

							<!--
									NOTE
									
									For a regular link, remove "dropdown" class from LI tag and "dropdown-toggle" class from the href.
									Direct Link Example: 

									<li>
										<a href="#">HOME</a>
									</li>
								-->
							<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
								<li class="active">
									<!-- HOME -->
									<a href="index.html">
										HOME
									</a>
								</li>
								<li>
									<!-- SERVICES -->
									<a href="index.html#services">
										SERVICES
									</a>
								</li>
								<li>
									<!-- WORK -->
									<a href="index.html#work">
										PORTFOLIO
									</a>
								</li>
								<li>
									<!-- NEWS -->
									<a href="index.html#news">
										NEWS
									</a>
								</li>

								<li>
									<!-- CLIENTS -->
									<a href="index.html#clients">
										CLIENTS
									</a>
								</li>


								<li>
									<!-- CONTACT -->
									<a href="index.html#contact">
										CONTACT
									</a>
								</li>


								<li>
									<!-- CONTACT -->
									<a href="career">
										CAREERS
									</a>
								</li>

								<li>
									<!-- CLIENTS -->
									<a href="admin">
										EMPLOYEE
									</a>
								</li>
							</ul>




			</header>


		</div>

 <%= yield %>

<footer id="footer">
			<div class="container">


				<div class="row">

					<!-- col #1 -->
					<div class="col-md-8">

						<h3 class="letter-spacing-1">A message from our president !</h3>
						<p>We have chosen to live by 3 core values: Integrity, Service, and Quality, and these words are more than a
							poster hanging in our office; each week we share stories of how these core values are being lived out by our
							team. I am very proud that we are a top TSSA elevator contractor in America, and that we were nominated for
							“Best Contractor in the World”. I am most pleased, however, by the comments we continually receive from our
							satisfied customers, as attested by our 4.9/5.0 Google Review Score and Comments. I hope you decide to give
							Elevator One a try. I am sure you won’t be disappointed.”</p>

						<!-- Small Description -->

						<span class="block"><strong><i class="fa fa-map-marker"></i> Address:</strong> Boulevard Lebourgneuf, Québec, QC
							G2J 0C4</span>
						<span class="block"><strong><i class="fa fa-phone"></i> Phone:</strong> <a href="tel:1800-555-1234">(418)
								580-7055</a></span>
						<span class="block"><strong><i class="fa fa-envelope"></i> Email:</strong> <a href="mailto:mail@yourdomain.com">rocketelevator@codeboxx.biz</a></span>
						</p>


					</div>
					<!-- /col #1 -->

					<!-- col #2 -->
					<div class="col-md-4">
						<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

						<!-- Newsletter Form -->
						<p>Subscribe to Our Newsletter to get Important News & Offers</p>

						<%= form_with(model: @subscription, local: true) do |form| %>

							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
								<input type="text" id="email" name="subscription" class="form-control required" placeholder="Enter your Email">
								<span class="input-group-btn">
									<button class="btn btn-danger" type="submit" href="thanks.html">Subscribe</button>
								</span>
							</div>
						</form>
						<% end %>
						<!-- /Newsletter Form -->


					</div>
					<!-- /col #2 -->

				</div>

			</div>

			<div class="copyright">
				<div class="container">
					<ul class="float-right m-0 list-inline mobile-block">

					</ul>
					&copy; All Rights Reserved, Rocket elevators.
				</div>
			</div>

		</footer>
        
	<script>var plugin_path = 'assets/plugins/';</script>

</body>

</html>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>