config/routes.rb
Rails.application.routes.draw do

  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/admin/graph_ql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root 'pages#index'
  get 'index' => 'pages#index'
  get 'residential' => 'pages#residential'
  get 'corporate' => 'pages#corporate'
  get 'quote' => 'quotes#new'
  get 'thanks' => 'pages#thanks'
  get 'thanksleads' => 'pages#thanksleads'
  get 'career' => 'careers#new'
  get 'subscription' => 'subscriptions#new'
  get 'thanksquote' => 'pages#thanksquote'
  get 'thankssubs' => 'pages#thankssubs'
  get 'watson' => 'watson#watson'
  get 'interventions' => 'index#interventions'
  post 'interventions' => 'index#interventions'

  get 'dropbox/auth' => 'dropbox#auth'
  get 'dropbox/auth_callback' => 'dropbox#auth_callback'

  resources :quotes
  resources :careers
  resources :subscriptions
  resources :leads
  resources :interventions
end

app/models/Intervention.rb
class Intervention < ApplicationRecord
    belongs_to :building
    establish_connection :development_pg
    self.table_name = 'fact_interventions'
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
    #before_action :set_intervention, only: [:show, :edit, :update, :destroy]
  
    # GET /interventions
    # GET /interventions.json
    def index
      @interventions = Intervention.all
    end
  
    # GET /interventions/1
    # GET /interventions/1.json
    def show
    end
  
    
    def getbuilding
  
      if params[:customer].present?
  
        @buildings = Customer.find(params[:customer]).buildings
      else
        @buildings = Building.all
      end
  
      render json: @buildings
    end
    
  
  
  
    # GET /interventions/new
    def new
      @intervention = Intervention.new
    end
  
    # GET /interventions/1/edit
    def edit
    end
  
    # POST /interventions
    # POST /interventions.json
    def create
      @intervention = Intervention.new(intervention_params)
  
      respond_to do |format|
        if @intervention.save
          format.html { redirect_to @intervention, notice: 'Intervention was successfully created.' }
          format.json { render :show, status: :created, location: @intervention }
        else
          format.html { render :new }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /interventions/1
    # PATCH/PUT /interventions/1.json
    def update
      respond_to do |format|
        if @intervention.update(intervention_params)
          format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
          format.json { render :show, status: :ok, location: @intervention }
        else
          format.html { render :edit }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /interventions/1
    # DELETE /interventions/1.json
    def destroy
      @intervention.destroy
      respond_to do |format|
        format.html { redirect_to interventions_url, notice: 'Intervention was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_intervention
        @intervention = Intervention.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def intervention_params
        params.fetch(:intervention, {})
      end
  end
  

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>



<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= link_to 'Show', intervention %></td>

<fieldset class="mt-60">
							<div class="row">
								<div class="col-md-6">
									<label for="contact_department"> Chose a client:</label>



<%= form_tag do %>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>




<% end %>
<% end %>


									<select id="building_type" class="form-control pointer" name="department">
										<option id="Non" value="None">--- Select ---</option>
                    
										<option id="Rsl" value="Residential">Clients</option><!-- //11 addR -->
									</select><br>
								</div>

							</div>
							<div>
								<!----------------------------------------------residential--------------------------------------------------------------------------------------------------------------------------------------------------->
								<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
								<div id="resiQ">

									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="ApartRes">How Many Appartement? *</label>
											<input id="NbApartRes" name="NbApartRes" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcRes()" onchange="CalcRes()" oninput="validity.valid||(value='')";/>
										</div>

									</div>
									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="FloorRes">How Many Floor? *</label>
											<input id="NbStageRes" name="NbStageRes"  novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcRes()" onchange="CalcRes()" oninput="validity.valid||(value='')"; />
										</div>

									</div>

									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="SsRes">How Many Basement? *</label>
											<input id="NbSsRes" name="NbSsRes" novalidate type="number" novalidate class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcRes()" onchange="CalcRes()" oninput="validity.valid||(value='')"; />
										</div>
									</div>
								</div>

								<!----------------------------------------Com----------------------------------------------------------------------------------------------------------------------------------------------------->
								<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
								<div id="comQ">

									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Separate Businesses? *</label>
											<input id="NbBusiCom" name="NbBusiCom" novalidate novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCom()"
											 onchange="CalcCom()" oninput="validity.valid||(value='')"; />
										</div>

									</div>
									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Floor? *</label>
											<input id="NbStageCom" name="NbStageCom" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCom()"
											 onchange="CalcCom()" oninput="validity.valid||(value='')";/>
										</div>

									</div>

									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Basement? *</label>
											<input id="NbSsCom" name="NbSsCom" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCom()"
											 onchange="CalcCom()" oninput="validity.valid||(value='')";/>
										</div>
									</div>
									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Parking? *</label>
											<input id="NbParkCom" name="NbParkCom" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCom()"
											 onchange="CalcCom()" oninput="validity.valid||(value='')"; />
										</div>

									</div>
									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Lift Cages To Deploy? *</label>
											<input id="NbCageCom" name="NbCageCom" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCom()" onchange="CalcCom()"oninput="validity.valid||(value='')"; />
										</div>

									</div>
								</div>

								<!---------------------------------------------------------------------Corporate------------------------------------------------------------------------------------------------------------------------>
								<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
								<div id="corpQ">

									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many separate tenant companies? *</label>
											<input id="NbBusiCorp" name="NbBusiCorp" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCorp()"
											 onchange="CalcCorp()" oninput="validity.valid||(value='')"; />
										</div>

									</div>
									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Floor? *</label>
											<input id="NbStageCorp" name="NbStageCorp" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCorp()"
											 onchange="CalcCorp()" oninput="validity.valid||(value='')"; />
										</div>

									</div>

									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Basement? *</label>
											<input id="NbSsCorp" name="NbSsCorp" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCorp()"
											 onchange="CalcCorp()" oninput="validity.valid||(value='')";/>
										</div>
									</div>
									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Parking? *</label>
											<input id="NbParkCorp" name="NbParkCorp" type="number" novalidate class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCorp()" onchange="CalcCorp()" oninput="validity.valid||(value='')"; />
										</div>
									</div>
									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">What Is The Maximum Number Of Occupants Per Floor? *</label>
											<input id="MaxOccCorp" name="MaxOccCorp" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcCorp()"
											 onchange="CalcCorp()" oninput="validity.valid||(value='')";/>
										</div>
									</div>
								</div>
								<!--------------------hybride-------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
								<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->

								<div id="hybQ">

									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Separate Businesses? *</label>
											<input id="NbBusiHyb" name="NbBusiHyb" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcHyb()"
											 onchange="CalcHyb()" oninput="validity.valid||(value='')"; />
										</div>

									</div>
									<div class="row">
										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Floor? *</label>
											<input id="NbStageHyb" name="NbStageHyb" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcHyb()"
											 onchange="CalcHyb()" oninput="validity.valid||(value='')"; />
										</div>

									</div>

									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Basement? *</label>
											<input id="NbSsHyb" name="NbSsHyb" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcHyb()" onchange="CalcHyb()" oninput="validity.valid||(value='')"; />
										</div>
									</div>
									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">How Many Parking? *</label>
											<input id="NbParkHyb" name="NbParkHyb" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcHyb()"
											 onchange="CalcHyb()" oninput="validity.valid||(value='')"; />
										</div>
									</div>
									<div class="row">

										<div class="col-md-12 col-sm-6">
											<label for="billing_email">What Is The Maximum Number Of Occupants Per Floor? *</label>
											<input id="MaxOccHyb" name="MaxOccHyb" novalidate type="number" class="form-control novalidate rst" min="0" max="10000" onkeyup="CalcHyb()"
											 onchange="CalcHyb()" oninput="validity.valid||(value='')"; />
										</div>
									</div>
									<div class="row">
										<div class="col-md-4">
											<label for="contact_department"> What Are The Opening Hours Of The Building? *</label>
											<input id="OppHourHyb" name="OppHourHyb" novalidate type="number" class="form-control novalidate rst" min="1" max="24" onkeyup="CalcHyb()"
											 onchange="CalcHyb()" oninput="validity.valid||(value='')"; />
											
										</div>

									</div>

								</div>

								<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
								<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->

						</fieldset>
						<!-- /BILLING -->

						<!-- /SHIPPING -->

					</div>


        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>